Update installation and configuration on Mac and Windows (#124)
* Check for appropriate version of node on Windows

* Check the installation configuration on Windows

* Name the extension "Hello World Panel Extension"

* Modify the elevation mechanism

* Create a script to keep failed windows open

* Add a note about scripts in Windows

* Correct Stack Overflow references

* Use a custom option parser

The built-in getopt command doesn't handle spaces properly.

* Check for appropriate version of node on Mac

* Correct certificate problems with Chrome on Mac

* Remove yarn ssl mechanisms

* Update documentation and rig references

* Add a script to delete certificates on Mac

diff --git a/scripts/make-cert b/scripts/make-cert
--- a/scripts/make-cert
+++ b/scripts/make-cert
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl
-# https://stackoverflow.com/questions/2129713
+# https://stackoverflow.com/questions/21297139/how-do-you-sign-a-certificate-signing-request-with-your-certification-authority
 
 # Check the platform.
 if [ "$(uname)" != "Darwin" ]; then
@@ -9,40 +9,37 @@ if [ "$(uname)" != "Darwin" ]; then
 	exit 1
 fi
 
-# Create the temporary directory.
-D=$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' $(dirname $0))
+# Create and switch to the temporary directory.
+D="$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$(dirname "$0")")"
 T=$(mktemp -d)
-cd "$T"
+cd $T
 
 # Clean up upon exit.
 on_exit() {
 	cd "$D"
-	rm -rf "$T"
+	rm -rf $T
 }
 trap on_exit EXIT
 
 # Create utility functions.
 fail() {
-	echo "$1"
+	echo -e "\033[0;31m$1\033[0m"
 	exit 1
 }
 check() {
 	[ $? -eq 0 ] || fail "Cannot $1."
 }
 
-# Determine if openssl needs to run to create the certificates.
+# Determine if the certificates need creation or installation.
 NEEDS_INSTALLATION=true
 SSL="$D/../ssl"
 if [ -s "$SSL/cacert.crt" -a -s "$SSL/cacert.key" -a -s "$SSL/selfsigned.crt" -a -s "$SSL/selfsigned.key" -a -s "$SSL/server.crt" -a -s "$SSL/server.key" ]; then
-	# The certificates have been previously created.  Determine if the CA certificate needs installation.
+	# The certificates have been previously created.  Determine if the certificates need installation.
 	security find-certificate -a | grep -Fq "Twitch Developer Rig CA" && NEEDS_INSTALLATION=false
 else
-	# Determine availability of OpenSSL.
+	# Determine the availability of OpenSSL.
 	openssl version > /dev/null 2>&1
-	if [ $? -ne 0 ]; then
-		echo OpenSSL is not available.
-		exit 1
-	fi
+	[ $? -eq 0 ] || fail "OpenSSL is not available."
 
 	# Prepare input files.
 	cp "$D"/*.cnf .
@@ -55,18 +52,18 @@ else
 	echo -e '\n\n\n\n\n\n\n' | openssl req -x509 -days 99999 -config $CA -newkey rsa:4096 -sha256 -nodes -out cacert.pem -outform PEM
 	check "create the certificate authority certificate"
 
-	# Create the certificate requests for the rig and localhost.
+	# Create the certificate requests for the Developer Rig and localhost.
 	echo "DNS.1 = localhost.rig.twitch.tv" > rig.dns
 	echo "DNS.1 = localhost" > localhost.dns
 	for i in rig localhost; do
 		rm openssl-server.cnf
 		cat "$D/openssl-server.cnf" $i.dns > openssl-server.cnf
 		echo -e '\n\n\n\n\n\n\n' | openssl req -config openssl-server.cnf -newkey rsa:2048 -sha256 -nodes -out ${i}cert.csr -outform PEM
-		check "create the %%I certificate request"
+		check "create the $i certificate request"
 		mv serverkey.pem ${i}key.pem
 	done
 
-	# Create the server certificates for the rig and localhost.
+	# Create the server certificates for the Developer Rig and localhost.
 	rm $CA
 	cat "$D/$CA" "$D/openssl-ca.add" > $CA
 	echo "unique_subject = no" > index.txt.attr
@@ -75,39 +72,52 @@ else
 		check "create the $i server certificate"
 	done
 
-	# Move all desired files to the rig ssl directory.
-	mv cacert.pem "$D/../ssl/cacert.crt"
-	mv cakey.pem "$D/../ssl/cacert.key"
-	mv rigcert.pem "$D/../ssl/selfsigned.crt"
-	mv rigkey.pem "$D/../ssl/selfsigned.key"
-	mv localhostcert.pem "$D/../ssl/server.crt"
-	mv localhostkey.pem "$D/../ssl/server.key"
-	check "place the developer rig certificates"
+	# Move all desired files to the Developer Rig ssl directory.
+	[ -s cacert.pem -a -s cakey.pem -a -s rigcert.pem -a -s rigkey.pem -a -s localhostcert.pem -a -s localhostkey.pem ] || fail "OpenSSL failed"
+	mv cacert.pem "$SSL/cacert.crt"
+	mv cakey.pem "$SSL/cacert.key"
+	mv rigcert.pem "$SSL/selfsigned.crt"
+	mv rigkey.pem "$SSL/selfsigned.key"
+	mv localhostcert.pem "$SSL/server.crt"
+	mv localhostkey.pem "$SSL/server.key"
+	check "place the Developer Rig certificate files"
 fi
 
 # Copy localhost certificates to the extension conf directory.
-mkdir -p "$D/../../my-extension/conf"
-cp "$D"/../ssl/server.* "$D/../../my-extension/conf"
-check "place the extension server certificates"
+CONF="$D/../../my-extension/conf"
+mkdir -p "$CONF"
+cp "$SSL"/server.* "$CONF"
+check "place the extension server certificate files"
 
-# Import the CA certificate into the local machine's root certificate store.
+# Add all certificates to the local machine's root certificate store.
 if $NEEDS_INSTALLATION; then
 	touch /etc/hosts 2> /dev/null || echo "Please enter your password to install the Twitch Developer Rig certificate."
-	sudo security add-trusted-cert -d -u -1 -k /Library/Keychains/System.keychain "$D/../ssl/cacert.crt"
-	check "import the CA certificate into the local machine's root certificate store"
+	sudo security add-trusted-cert -d -p ssl -u -1 -k /Library/Keychains/System.keychain "$SSL/cacert.crt"
+	check "add the CA certificate to the local machine's root certificate store"
+	for name in server selfsigned; do
+		sudo security add-trusted-cert -d -p ssl -r trustAsRoot -k /Library/Keychains/System.keychain "$SSL/$name.crt"
+		check "add the $name certificate to the local machine's root certificate store"
+	done
 
 	# If Firefox is installed, allow it to use the certificates in the local
 	# machine's root certificate store.
 	FF=/Applications/Firefox.app/Contents/Resources
-	if [ -d $FF/defaults/pref ]; then
-		echo 'pref("security.enterprise_roots.enabled", true);' > $FF/defaults/pref/twitch-developer-rig.js
+	if [ -d $FF ]; then
+		FF_PREF=$FF/defaults/pref
+		FF_RIG=$FF_PREF/twitch-developer-rig.js
+		cat > $FF_RIG <<- EOF
+			// Twitch preferences
+			pref("security.enterprise_roots.enabled", true);'
+		EOF
+		check "create $FF_RIG"
 
 		# Due to Mozilla bug 1300420, the preference specified above isn't
-		# sufficient to trust the certificates.  The following will add the root CA
-		# certificate to Firefox's trust store.
+		# sufficient to trust the certificates.  The following will add the root
+		# CA certificate to Firefox's trust store.
 		# https://github.com/soberhofer/Firefox-RootCA
-		CFG=$FF/mozilla.cfg
-		cat >> $CFG <<- EOF
+		FF_CFG=$FF/mozilla.cfg
+		sed '/Twitch Developer Rig CA certificate addition/,$d' $FF_CFG > cfg
+		cat >> cfg <<- EOF
 			// Twitch Developer Rig CA certificate addition
 			var Cc = Components.classes;
 			var Ci = Components.interfaces;
@@ -117,14 +127,24 @@ if $NEEDS_INSTALLATION; then
 			"";
 			certdb.addCertFromBase64(twitchCert, "C,C,C", "");
 		EOF
+		mv cfg $FF_CFG
+		check "update $FF_CFG"
+
+		# Ensure Firefox uses the above file.
+		if ! grep -Fq general.config $FF_PREF/*; then
+			cat >> $FF_RIG <<- EOF
+				pref("general.config.obscure_value",0);
+				pref("general.config.filename","mozilla.cfg");
+			EOF
+		fi
 	fi
 
 	# The user must restart their browser for these changes to take effect.
 	if [ $# -eq 0 ]; then
-		echo -e '\033[1;33mNOTE:\033[0;33m  you must restart your browser before running the developer rig.\033[0m'
+		echo -e '\033[1;35mNOTE:\033[0;35m  you must restart your browser before running the Developer Rig.\033[0m'
 	else
-		echo -e '\033[1;33mNOTE:\033[0;33m  you must restart your browser before continuing.\033[0m'
+		echo -e '\033[1;35mNOTE:\033[0;35m  you must restart your browser before continuing.'
+		echo -e 'Press "return" to acknowledge.\033[0m'
+		read L
 	fi
-	echo 'Press "return" to acknowledge.'
-	read L
 fi
