Realize the concept of a Project (#180)
* Implement projects

* Copy SSL certificates

* Perform back-end command variable substitutions

* Update projects for local mode

* Conditionally allow pre-existing project folder

* Conditionally allow empty project folders

* Use BEM to style the project view

* Use BEM to style the "create project" dialog

* Create the project drop-down menu

* Move extension views into the project

* Shut down hosting, if necessary

* Create a property for the current project index

* Improve front-end hosting

It now creates a cross-platform implementation that doesn't rely on a
shell to execute the command.  As a result, the child process can be
killed instead of only the spawning shell.

* Improve back-end hosting

With the assistance of a newly-required library, this implementation
mimics that of the front-end hosting.

* Stop hosting when creating a project

* Implement the mock trigger bar

* Implement mock trigger messaging

* Move mock trigger bar to extension view container

* Open tabs for documentation and tutorial

* Provide error feedback in "create project" dialog

* Implement explicitly stopping hosting

* Disable project name textbox for online extensions

For online extensions, the name is taken from the extension.  There is a
tooltip to describe the situation.

* Remove installation and configuration of Git

* Simplify the "run" script

* Add iconUrls field to ExtensionObject class

* Remove the extension manifest from local storage

This will more easily allow updating the manifest.

* Refresh online manifest if requested

* Remove "Generate Scaffolding" option

No scaffolding projects are yet available.

* Cut Down the Read Me to Just Quick Start and Trouble Shooting

Since we are moving our docs onto the dev site, the readme has been significantly simplified.

* Replace HTML-based README with PDF

Updating the documentation reflect the new state of the world

* Add Windows 10 troubleshooting

Line discusses needing to have your security settings to Developer Mode

* Automatically scroll the console as necessary

* Replace trigger switch HTML with SVG

* Create platform-agnostic back-end command

* Implement custom front-end hosting

* Remove install and configure from run

The run scripts will issue a warning and fail to run if the
configuration is not valid.

* Create a single certificate for both DNS entries

Use both localhost and localhost.rig.twitch.tv as DNS entries in the
generated certificate.  This certificate is good for hosting the front-
and back-end of an extension in either domain.

* Default extension visibility to true

* Create project folder only, if requested

* Use React ref in the console

* Protect against missing client ID

* Use spawn instead of spawnSync

Using spawnSync causes the Node event loop to hang.  This disrupts the
networking sufficiently to cause random errors (e.g. client-side network
error and mysterious restarting of a POST request).

* Remove unnecessary import directives

diff --git a/scripts/make-cert b/scripts/make-cert
--- a/scripts/make-cert
+++ b/scripts/make-cert
@@ -34,7 +34,7 @@ check() {
 # Determine if the certificates need creation or installation.
 NEEDS_INSTALLATION=true
 SSL="$D/../ssl"
-if [ -s "$SSL/cacert.crt" -a -s "$SSL/cacert.key" -a -s "$SSL/selfsigned.crt" -a -s "$SSL/selfsigned.key" -a -s "$SSL/server.crt" -a -s "$SSL/server.key" ]; then
+if [ -s "$SSL/cacert.crt" -a -s "$SSL/cacert.key" -a -s "$SSL/selfsigned.crt" -a -s "$SSL/selfsigned.key" ]; then
 	# The certificates have been previously created.  Determine if the certificates need installation.
 	security find-certificate -a | grep -Fq "Twitch Developer Rig CA" && NEEDS_INSTALLATION=false
 else
@@ -43,62 +43,42 @@ else
 	[ $? -eq 0 ] || fail "OpenSSL is not available."
 
 	# Prepare input files.
-	cp "$D"/*.cnf .
 	touch index.txt
 	openssl rand -hex 4 > serial.txt
-	cat serial.txt
-	CA=openssl-ca.cnf
 
 	# Create the certificate authority certificate.
-	echo -e '\n\n\n\n\n\n\n' | openssl req -x509 -days 99999 -config $CA -newkey rsa:4096 -sha256 -nodes -out cacert.pem -outform PEM
+	echo -e '\n\n\n\n\n\n\n' | openssl req -x509 -days 99999 -config "$D/openssl-ca.cnf" -newkey rsa:4096 -sha256 -nodes -out cacert.pem -outform PEM
 	check "create the certificate authority certificate"
 
 	# Create the certificate requests for the Developer Rig and localhost.
-	echo "DNS.1 = localhost.rig.twitch.tv" > rig.dns
-	echo "DNS.1 = localhost" > localhost.dns
-	for i in rig localhost; do
-		rm openssl-server.cnf
-		cat "$D/openssl-server.cnf" $i.dns > openssl-server.cnf
-		echo -e '\n\n\n\n\n\n\n' | openssl req -config openssl-server.cnf -newkey rsa:2048 -sha256 -nodes -out ${i}cert.csr -outform PEM
-		check "create the $i certificate request"
-		mv serverkey.pem ${i}key.pem
-	done
+	cp "$D/openssl-server.cnf" .
+	echo "DNS.1 = localhost.rig.twitch.tv" >> openssl-server.cnf
+	echo "DNS.2 = localhost" >> openssl-server.cnf
+	echo -e '\n\n\n\n\n\n\n' | openssl req -config openssl-server.cnf -newkey rsa:2048 -sha256 -nodes -out servercert.csr -outform PEM
+	check "create the certificate request"
 
 	# Create the server certificates for the Developer Rig and localhost.
-	rm $CA
-	cat "$D/$CA" "$D/openssl-ca.add" > $CA
+	cat "$D/openssl-ca.cnf" "$D/openssl-ca.add" > openssl-ca.cnf
 	echo "unique_subject = no" > index.txt.attr
-	for i in rig localhost; do
-		yes | openssl ca -config $CA -policy signing_policy -extensions signing_req -out ${i}cert.pem -infiles ${i}cert.csr
-		check "create the $i server certificate"
-	done
+	yes | openssl ca -config openssl-ca.cnf -policy signing_policy -extensions signing_req -out servercert.pem -infiles servercert.csr
+	check "create the server certificate"
 
 	# Move all desired files to the Developer Rig ssl directory.
-	[ -s cacert.pem -a -s cakey.pem -a -s rigcert.pem -a -s rigkey.pem -a -s localhostcert.pem -a -s localhostkey.pem ] || fail "OpenSSL failed"
+	[ -s cacert.pem -a -s cakey.pem -a -s servercert.pem -a -s serverkey.pem ] || fail "OpenSSL failed"
 	mv cacert.pem "$SSL/cacert.crt"
 	mv cakey.pem "$SSL/cacert.key"
-	mv rigcert.pem "$SSL/selfsigned.crt"
-	mv rigkey.pem "$SSL/selfsigned.key"
-	mv localhostcert.pem "$SSL/server.crt"
-	mv localhostkey.pem "$SSL/server.key"
+	mv servercert.pem "$SSL/selfsigned.crt"
+	mv serverkey.pem "$SSL/selfsigned.key"
 	check "place the Developer Rig certificate files"
 fi
-
-# Copy localhost certificates to the extension conf directory.
-CONF="$D/../../my-extension/conf"
-mkdir -p "$CONF"
-cp "$SSL"/server.* "$CONF"
-check "place the extension server certificate files"
 
 # Add all certificates to the local machine's root certificate store.
 if $NEEDS_INSTALLATION; then
 	touch /etc/hosts 2> /dev/null || echo "Please enter your password to install the Twitch Developer Rig certificate."
 	sudo security add-trusted-cert -d -p ssl -u -1 -k /Library/Keychains/System.keychain "$SSL/cacert.crt"
 	check "add the CA certificate to the local machine's root certificate store"
-	for name in server selfsigned; do
-		sudo security add-trusted-cert -d -p ssl -r trustAsRoot -k /Library/Keychains/System.keychain "$SSL/$name.crt"
-		check "add the $name certificate to the local machine's root certificate store"
-	done
+	sudo security add-trusted-cert -d -p ssl -r trustAsRoot -k /Library/Keychains/System.keychain "$SSL/selfsigned.crt"
+	check "add the certificate to the local machine's root certificate store"
 
 	# If Firefox is installed, allow it to use the certificates in the local
 	# machine's root certificate store.
diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -6,86 +6,14 @@ if [ "$(uname)" != "Darwin" ]; then
 	exit 1
 fi
 
-# Create utility functions.
-getfullpath() {
-	python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$1"
-}
-fail() {
-	echo -e "\033[0;31m$1\033[0m"
+# Ensure the configuration is up to date.
+cd "$(dirname "$0")/.."
+[ .configured -nt package.json ] || yarn install
+if [ $? -ne 0 ]; then
+	echo -e "\033[0;31mconfiguration update failed\033[0m"
 	exit 1
-}
-cannot() {
-	[ $? -eq 0 ] || fail "Cannot $1."
-}
-usage() {
-	echo "usage: $0 [-m manifest-file] [-f front-end-directory] [-b back-end-file]"
-	[ "$1" = "-h" -o "$1" = "--help" ] && exit 0 || exit 2
-}
-
-# Run the configuration script first.
-D=$(dirname "$0")
-"$D/configure" - || exit 1
-
-# Collect command line parameters or provide defaults.
-D=$(getfullpath "$D"/..)
-P=$(getfullpath "$D"/..)
-if [ $# -eq 0 ]; then
-	MANIFEST_FILE="$P/panel.json"
-	FRONTEND_DIRECTORY="$P/my-extension"
-	BACKEND_FILE="$P/my-extension/services/backend.js"
-else
-	while [ $# -gt 0 ]; do
-		if [ "$1" = "-b" ]; then
-			BACKEND_FILE="$2";
-			[ -s "$BACKEND_FILE" ] || cannot "open back-end file '$BACKEND_FILE'"
-			BACKEND_FILE=$(getfullpath "$2");
-			shift
-		elif [ "$1" = "-f" ]; then
-			FRONTEND_DIRECTORY="$2";
-			[ -d "$FRONTEND_DIRECTORY" ] || cannot "open front-end directory '$FRONTEND_DIRECTORY'"
-			FRONTEND_DIRECTORY=$(getfullpath "$2");
-			shift
-		elif [ "$1" = "-m" ]; then
-			MANIFEST_FILE="$2";
-			[ -s "$MANIFEST_FILE" ] || cannot "open manifest file '$MANIFEST_FILE'"
-			MANIFEST_FILE=$(getfullpath "$2");
-			shift
-		else
-			usage "$1"
-		fi
-		shift
-	done
 fi
+touch .configured
 
-# For the "hello world" extension, ensure service of the correct directory.
-[ -n "$FRONTEND_DIRECTORY" -a -d "$FRONTEND_DIRECTORY/public" ] && FRONTEND_DIRECTORY="$FRONTEND_DIRECTORY/public"
-
-# If necessary, create a panel extension manifest file.
-cd "$D"
-[ -n "$MANIFEST_FILE" ] || MANIFEST_FILE="$P/panel.json"
-if [ -s "$MANIFEST_FILE" ]; then
-	echo "Using extension manifest in '$MANIFEST_FILE'."
-else
-	echo "Creating and using panel extension manifest in '$MANIFEST_FILE'."
-	yarn create-manifest -t panel -o "$MANIFEST_FILE"
-fi
-
-# Start new processes for the different aspects of running the Developer Rig.
-NPROCESSES=0
-if [ -z "$FRONTEND_DIRECTORY" ]; then
-	echo "Front-end hosting is not being provided by the Developer Rig."
-else
-	echo "Hosting front-end in '$FRONTEND_DIRECTORY'."
-	yarn host -d "$FRONTEND_DIRECTORY" -p 8080 -l &
-	NPROCESSES=$(expr $NPROCESSES + 1)
-fi
-if [ -z "$BACKEND_FILE" ]; then
-	echo "Back-end hosting is not being provided by the Developer Rig."
-else
-	echo "Hosting back-end in '$BACKEND_FILE'."
-	node "$BACKEND_FILE" -l "$MANIFEST_FILE" &
-	NPROCESSES=$(expr $NPROCESSES + 1)
-fi
-[ $NPROCESSES -gt 1 ] && ES=es
-[ $NPROCESSES -gt 0 ] && echo "Started $NPROCESSES other process$ES to run the Developer Rig."
-yarn start -l "$MANIFEST_FILE"
+# Start the Developer Rig.
+yarn start
