Modify scripts to support Linux

diff --git a/scripts/make-cert b/scripts/make-cert
--- a/scripts/make-cert
+++ b/scripts/make-cert
@@ -6,8 +6,8 @@
 # https://www.shellhacks.com/create-csr-openssl-without-prompt-non-interactive/
 
 # Check the platform.
-if [ "$(uname)" != "Darwin" ]; then
-	echo "This script is for Mac only."
+if [ "$(uname)" != "Linux" -a "$(uname)" != "Darwin" ]; then
+	echo "This script is for Linux or Mac only."
 	exit 1
 fi
 
@@ -37,7 +37,11 @@ NEEDS_INSTALLATION=true
 SSL="$D/../ssl"
 if [ -s "$SSL/cacert.crt" -a -s "$SSL/cacert.key" -a -s "$SSL/selfsigned.crt" -a -s "$SSL/selfsigned.key" ]; then
 	# The certificates have been previously created.  Determine if the certificates need installation.
-	security find-certificate -a | grep -Fq "Twitch Developer Rig CA" && NEEDS_INSTALLATION=false
+	if [ "$(uname)" != "Linux" ]; then
+		trust list | grep -Fq "Twitch Developer Rig CA" && NEEDS_INSTALLATION=false
+	else
+		security find-certificate -a | grep -Fq "Twitch Developer Rig CA" && NEEDS_INSTALLATION=false
+	fi
 else
 	# Determine the availability of OpenSSL.
 	openssl version > /dev/null 2>&1
@@ -73,9 +77,27 @@ else
 	check "place the Developer Rig certificate files"
 fi
 
-# Add all certificates to the local machine's root certificate store.
-if $NEEDS_INSTALLATION; then
-	touch /etc/hosts 2> /dev/null || echo "Please enter your password to install the Twitch Developer Rig certificate."
+install_for_linux() {
+	if [ -d "/usr/local/share/ca-certificates" ]; then
+		local dest="/usr/local/share/ca-certificates/twitch-developer-rig"
+		touch /etc/hosts 2> /dev/null || echo "Please enter your password to install the Twitch Developer Rig certificate."
+		if [ ! -d "${dest}" ]; then
+			sudo mkdir -p "${dest}"
+		fi
+		for name in server selfsigned; do
+			echo "$name.crt"
+			sudo cp "${name}.crt" "${dest}/{$name}.crt"
+			check "add the $name certificate to the local machine's root certificate store"
+		done
+		sudo update-ca-certificates
+	else
+		echo -e '\033[1;35mNOTE:\033[0;35m  Unable to determine certificate destination on your machine.'
+		echo -e '\033[1;35mNOTE:\033[0;35m  Please manually install ssl/server.crt and ssl/selfsigned.crt to the global trust.'
+	fi
+	echo -e '\033[1;35mNOTE:\033[0;35m  If you are using Firefox, you may have to manually add certs to avoid trust errors.'
+}
+
+install_for_mac() {
 	sudo security add-trusted-cert -d -p ssl -u -1 -k /Library/Keychains/System.keychain "$SSL/cacert.crt"
 	check "add the CA certificate to the local machine's root certificate store"
 	sudo security add-trusted-cert -d -p ssl -r trustAsRoot -k /Library/Keychains/System.keychain "$SSL/selfsigned.crt"
@@ -123,6 +145,12 @@ if $NEEDS_INSTALLATION; then
 		# Update Firefox's preferences.
 		sudo mv $FF_RIG $FF_PREF
 	fi
+}
+
+if $NEEDS_INSTALLATION; then
+	# Add all certificates to the local machine's root certificate store.
+	touch /etc/hosts 2> /dev/null || echo "Please enter your password to install the Twitch Developer Rig certificate."
+	[ "$(uname)" != "Linux" ] && install_for_linux || install_for_mac
 
 	# The user must restart their browser for these changes to take effect.
 	if [ $# -eq 0 ]; then
